//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<catalogo_parte_principal> catalogo_parte_principal { get; set; }
        public virtual DbSet<catalogo_parte_secundaria> catalogo_parte_secundaria { get; set; }
        public virtual DbSet<emp_empleado> emp_empleado { get; set; }
        public virtual DbSet<orde_detalle> orde_detalle { get; set; }
        public virtual DbSet<orden> orden { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<per_persona> per_persona { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ve_vehiculo> ve_vehiculo { get; set; }
        public virtual DbSet<ve_vehiculo_color> ve_vehiculo_color { get; set; }
        public virtual DbSet<ve_vehiculo_marca> ve_vehiculo_marca { get; set; }
        public virtual DbSet<ve_vehiculo_modelo> ve_vehiculo_modelo { get; set; }
        public virtual DbSet<ve_vehiculo_responsable> ve_vehiculo_responsable { get; set; }
        public virtual DbSet<ve_vehiculo_tipo> ve_vehiculo_tipo { get; set; }
    }
}
